[default]

salt_master = { name = "", host = "", os_type = "linux", linux_distro = ""}
salt_minions = [
    { name = "", host = "", os_type = "linux", linux_distro = "" }
]

[dev]

salt_master = { name = "<master name/id", host = "<master ip/fqdn>", os_type = "linux", linux_distro = "ubuntu"}
salt_minions = [
    { name = "<minion name/id>", host = "<minion ip/fqdn>", os_type = "linux", linux_distro = "ubuntu" }
]

[prod]
